verdigado/sunflower

functions/activation.php
=> Fix Activation warning

functions.php
=> Removes the generator meta tag from the theme

template-parts/event-json-ld.php
=> Bugfix OfflineEventAttendanceMode

functions/options/settings.php, single.php
Deutsche Übersetzung fehlt noch
=> Option zum verstecken der Vor/Zurück Links

.github/workflows/build-deploy.yml, .gitignore, functions/icalimport.php
This is a different fix for the error reported in #393
=> Avoid PHP error if ics calendar cannot be reached

functions/ical.php
=> Fix ics character encoding and length of description field

sass/_variables.scss
=> Use same color identifiers in theme and SCSS

functions/_s.php, js/customizer.js, package-lock.json, sass/_variables.scss, sass/_widgets.scss
=> Fix block background with color gray

assets/css/editor-style.css, assets/custom-jquery-date-time-picker.js, functions/events.php
=> Set end of event to start of event in Datepicker

archive-sunflower_event.php
Update der archive-sunflower_event.php mit eigener Class für den Kalender Downloadlink, um über die neue Class "calendar-download" den Link individuell zu stylen.
Hintergrund: Unser Kreisverband hätte den Link gerne größer und deutlicher gestyled.
=> Update der archive-sunflower_event.php, Kalenderdownload

functions/options/settings.php, mkdocs/docs/setup.md, template-parts/header-personal.php
CSS class `nowrap` seems to be unused. This PR removes it from template.
=> Remove unused nowrap class

sass/_navigation.scss
Possible fix for #451.
Another approach to #462 
Looks like this (with hover):
=> Highlight active parent menu item if sub-sub entry is selected

sass/_footer.scss, sass/_variables.scss
=> Use only one dark green in footer

sass/_accordion.scss
Schöneres Akkordeon durch Verwenden unseres Farbschematas und übersichtlicherer gestaltung.
=> Anpassung Style für Plugin accordion-blocks

functions/activation.php
Thanks to @weissgruenbunt for contribution!
=> Fix #498: import all events from urwahl3000 including thumbnails

sass/_colors.scss, sass/_comments.scss, sass/_event.scss, sass/_footer.scss, sass/_generic.scss, sass/_layout.scss, sass/_meta.scss, sass/_typography.scss, sass/_variables.scss, sass/_widgets.scss, sass/abstracts/variables/_colors.scss, sass/base/elements/_links.scss, sass/components/navigation/_navigation.scss, sass/wp-blocks/_blocks.scss, sass/wp-blocks/button.scss
=> Enhance accessability with focused links and keyboard navigation

assets/css/editor-style.css, assets/js/frontend.js, functions/_s.php, sass/style.scss, sass/wp-blocks/_blocks.scss, sass/wp-blocks/rss.scss
This partly fixes #517. Missing feature are images in rss feeds.
=> Add basic styling to WordPress RSS block

assets/css/editor-style.css, sass/_typography.scss
add the css class .textbalken to create the Textbalken (background in the form of a parallelogram) of the green CI.
=> Textbalken

assets/css/editor-style.css, sass/_typography.scss
corr the padding of textbalken
=> Fix padding of textbalken

sass/_header.scss, template-parts/header-personal.php, template-parts/header-standard.php
Add the green Background behind the sunflower. The design is inspired by the new design of gruene.de
=> Green Background at Logo

mkdocs/docs/customcss.md
closes https://github.com/verdigado/sunflower/issues/614
=> Docs: custom CSS for background logo color in personal-header

sass/_fonts.scss
Fix Bug font-style 400 to normal
=> fix font-style

sass/style.scss
Corporate Design: https://design.gruene.de/4ccd94a80/p/0558bf-sprache-und-schrift
=> Fix party name in style.scss

inc/class-wp-bootstrap-navwalker.php, theme.json
=> Update navigation walker and close custom <div>

mkdocs/docs/donationform.md, mkdocs/docs/plugins.md, mkdocs/mkdocs.yml
https://netz.gruene.de/de/wissenswerk/2021-03/online-fundraising-spenden-tool-formular-fuer-gliederungen
=> Docs: add infos about donation form

sass/_single.scss
=> Set padding to 15px 0 in display-single

page.php, sass/_archives.scss, sass/_layout.scss, sass/_single.scss, template-parts/content-page.php, template-parts/header-standard.php
=> Unify header title padding on content and category/archive pages
